### ISSUE TITLE
Need to rebuild rpp everytime a different gpu is used.

### ISSUE THREAD

**Issue by GowthamKudupudi** [GPUOpen-ProfessionalCompute-Libraries/rpp#149]
RPP needs a rebuild everytime a different gpu is used; this blocks me from pre-building RPP into a docker image and distributing it.
I'm using the commit `27284078458fbfa685f11083315394f3a4cd952f`. is it a known issue and is fixed in recent versions?

**Comment by LakshmiKumar23** [comment]
Hi @GowthamKudupudi, RPP does not need to be built every time a different GPU is used. Please try with master branch TOT.

**Comment by kiritigowda** [comment]
@GowthamKudupudi are you still facing this issue with TOT? Please let us know, thanks!

**Comment by kiritigowda** [comment]
@GowthamKudupudi please reopen this issue if you are still facing this issue. Thanks!
