### ISSUE TITLE
library install missing for rpp build on ub22 & rocm5.5

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/rpp#151]
@kiritigowda requires this install to build on rocm5.5/ub22
```
sudo apt install g++-12
```

**Comment by kiritigowda** [comment]
@LakshmiKumar23 the RPP library does not have a setup script. Do you want to add this to readme? or did you want to create an issue on MIVisionX setup? I yes on both, can you create a PR?

**Comment by kiritigowda** [comment]
@LakshmiKumar23 ??

**Comment by kiritigowda** [comment]
Do we still require this @LakshmiKumar23 ?

**Comment by kiritigowda** [comment]
@LakshmiKumar23 reopen if you still see this.
