### ISSUE TITLE
AMD GPU Arch - Deprecated

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/rpp#192]
gcnArch was deprecated in ROCm 3.7. Instead, gcnArchName was introduced. gcnArch was never removed but announced that it will be done in ROCm 5.5 via https://rocm.docs.amd.com/en/docs-5.5.1/CHANGELOG.html#future-changes. So now it is intended to be done in ROCm 6.0.

gcnArch present in RPP source code at below places:

Can you please review the below lines of code and stop using gcnArch if still used:

src/modules/hip/handlehip.cpp:    std::string n("gfx" + std::to_string(props.gcnArch));
src/modules/hip/hipoc_program.cpp:      std::string gfxName = "gfx" + std::to_string(props.gcnArch);

**Comment by rrawther** [comment]
fixed in PR#199

**Comment by kiritigowda** [comment]
#199

**Comment by kiritigowda** [comment]
Fix on TOT
