### ISSUE TITLE
CMakeList - MIOpen Dependencies

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/rpp#29]
MIOpen Dependencies should be removed from RPP.

```
-- AMDGCN assembler: MIOPEN_AMDGCN_ASSEMBLER-NOTFOUND
```

**Comment by kiritigowda** [comment]
@LokeshBonta can you look at this issue

**Comment by LokeshBonta** [comment]
@kiritigowda  Created a PR 
[](https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp/pull/30)

**Comment by kiritigowda** [comment]
#30 merged.
