### ISSUE TITLE
HIP Backend - RPP not building

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/rpp#34]

**Comment by rrawther** [comment]
@LokeshBonta : Can you please check this issue. I am getting many compile errors

**Comment by kiritigowda** [comment]
@shobana-mcw can you look into this.

**Comment by shobana-mcw** [comment]
We have resolved this issue. 
@r-abishekmcw Please create a PR for the HIP CMake changes.

**Comment by r-abishekmcw** [comment]
@kiritigowda Please view #36 . The hip build was tested inside kiritigowda/ubuntu-18.04:rocm-3.8

**Comment by kiritigowda** [comment]
@rrawther the PR #36 is merged, let me know if you are finding HIP compilation errors. If not, you can close this issue.

**Comment by kiritigowda** [comment]
@paveltc and @rrawther is this fixed?

**Comment by rrawther** [comment]
@kiritigowda : waiting for @shobana-mcw to make a PR after it is fixed.

**Comment by rrawther** [comment]
This should already be fixed. @paveltc please confirm that you ran all the unit tests for the HIP backend.

**Comment by paveltc** [comment]
@rrawther and @kiritigowda I will run the tests and give an update.

**Comment by rrawther** [comment]
Resolved with the PR
