### ISSUE TITLE
RPP Branch - Develop & Batch Enabled

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/rpp#40]
The Old Branches are diverging from the master. Should be refactor the branches into a single branch or delete them if?

- [x] Develop
- [x] Batch Enabled

**Comment by rrawther** [comment]
I think we can delete Batch Enabled. Keep develop sync with master for future

**Comment by kiritigowda** [comment]
Stale branches deleted
