### ISSUE TITLE
Test - Unit test 

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/rpp#42]
* Instructions unclear - [here](https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp/tree/master/test/rpp_unittests#steps-to-compile-build-and-test)

* Hard code paths - Examples below

  + https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp/blob/c2527d5b637c2c08a818b28e51547d892a36d398/test/rpp_unittests/geometric-tests/Test_Scripts/Support_Code.py#L5

  + https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp/blob/c2527d5b637c2c08a818b28e51547d892a36d398/test/rpp_unittests/majority-tests/Support_Code.py#L5

  + https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp/blob/c2527d5b637c2c08a818b28e51547d892a36d398/test/rpp_unittests/majority-tests/csv%20files.txt#L1

**Comment by kiritigowda** [comment]
@paveltc please track this issue. Need this for unit tests.

**Comment by kiritigowda** [comment]
@r-abishekmcw & @shobana-mcw - Can you take a look at this, please model unit tests from [here]( https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/tests/neural_network_tests#mivisionx-neural-network-tests)

**Comment by kiritigowda** [comment]
@r-abishekmcw can we close this?

**Comment by r-abishekmcw** [comment]
@kiritigowda Yes, we could close this one. The unittests for rpp have now completely changed from this one.
