### ISSUE TITLE
RPP Unit Tests - Update readme for all tests, run config (input and output) and how to configure for different input

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/rpp#48]

**Comment by kiritigowda** [comment]
@paveltc can you follow up on these tests with @r-abishek, we need to enable these on the CI

**Comment by paveltc** [comment]
@kiritigowda I will follow up with him.

**Comment by r-abishek** [comment]
@paveltc @kiritigowda For now, a very simple CI setup that I currently have on my fork (to just run checks before I PR into GPUopen) is 4 different workflows (for host/ocl/hiprtc/hip static) running on a docker on a self-hosted server. (Each just runs respective build followed by performancetests) https://github.com/r-abishek/rpp/actions

**Comment by kiritigowda** [comment]
closing this issue and creating a new one to add tests into CI
