### ISSUE TITLE
CI - Unit Tests

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/rpp#58]
CI missing unit tests

**Comment by kiritigowda** [comment]
#64 adds functionality, @paveltc need to add this test feature to CI

**Comment by paveltc** [comment]
@kiritigowda I'll take a look at what can be added to the CI. The unit tests for RPP are comprehensive and take up a lot of time. Not sure if the CI is the proper place for them.

**Comment by kiritigowda** [comment]
Issue #74 track
