### ISSUE TITLE
RPP tot gives compile errors with MIVisionX master

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/rpp#69]
@r-abishek: I this this happened with the merge of your last PR.
Can you please check and provide fix.

**Comment by kiritigowda** [comment]
With V0.91 TOT issue is resolved. - PR - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/629
adds this to MIVisionX

**Comment by kiritigowda** [comment]
TOT Merged and verified with MIVisionX CI
