### ISSUE TITLE
BUILD - RPP takes a really long time to compile

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/rpp#91]

**Comment by rrawther** [comment]
@kiritigowda @asalmanp : this is still happening. After 99% it is taking a long time to finish

**Comment by kiritigowda** [comment]
any resolution for this @asalmanp @rrawther -- HIP backend takes 4+ minutes with -j8

**Comment by rrawther** [comment]
This is not observed anymore
